export const SIZE_OPTIONS = [
  { slug: "solo", label: "Solo / Bootstrapped (1–10)" },
  { slug: "small", label: "Small (11–50)" },
  { slug: "mid", label: "Mid-size (51–200)" },
  { slug: "large", label: "Large (201–1000)" },
  { slug: "enterprise", label: "Enterprise (1000+)" },
]

export const INDUSTRY_OPTIONS = [
  { slug: "technology", label: "Technology / Software" },
  { slug: "finance", label: "Finance / Banking" },
  { slug: "healthcare", label: "Healthcare" },
  { slug: "education", label: "Education" },
  { slug: "retail", label: "Retail / E-commerce" },
  { slug: "media", label: "Media / Entertainment" },
  { slug: "nonprofit", label: "Non-profit / Mission-driven" },
  { slug: "government", label: "Government / Public Sector" },
  { slug: "consulting", label: "Consulting / Professional Services" },
  { slug: "manufacturing", label: "Manufacturing" },
  { slug: "realestate", label: "Real Estate" },
  { slug: "energy", label: "Energy / Utilities" },
  { slug: "hospitality", label: "Hospitality / Travel" },
  { slug: "legal", label: "Legal" },
]

export const CULTURE_OPTIONS = [
  { slug: "remote-first", label: "Remote-first" },
  { slug: "hybrid", label: "Hybrid" },
  { slug: "in-office", label: "In-office" },
  { slug: "fast-paced", label: "Fast-paced / Startup energy" },
  { slug: "stable", label: "Stable / Steady" },
  { slug: "collaborative", label: "Collaborative" },
  { slug: "autonomous", label: "Autonomous" },
  { slug: "structured", label: "Highly structured" },
  { slug: "casual", label: "Casual / Informal" },
  { slug: "formal", label: "Formal / Professional" },
]

export const VALUES_OPTIONS = [
  { slug: "innovation", label: "Innovation" },
  { slug: "work-life", label: "Work-life balance" },
  { slug: "dei", label: "Diversity & inclusion" },
  { slug: "mission-driven", label: "Mission-driven" },
  { slug: "career-growth", label: "Career growth" },
  { slug: "learning", label: "Learning & development" },
  { slug: "compensation", label: "Compensation" },
  { slug: "stability", label: "Stability & security" },
  { slug: "sustainability", label: "Sustainability / Environmental" },
  { slug: "customer-obsessed", label: "Customer-obsessed" },
  { slug: "transparency", label: "Transparency" },
  { slug: "recognition", label: "Recognition" },
]

export const QUIZ_QUESTIONS = [
  {
    key: "size",
    title: "What size of company feels right?",
    subtitle: "Pick all the sizes you would seriously consider. There is no wrong answer. 🏢",
    options: SIZE_OPTIONS,
    allowCustom: false,
    required: true,
    standardCol: "size_standard",
    customCol: null,
  },
  {
    key: "industry",
    title: "Which industries are you drawn to?",
    subtitle: "Pick any that fit. Add your own if we missed one. 🌱",
    options: INDUSTRY_OPTIONS,
    allowCustom: true,
    required: true,
    standardCol: "industry_standard",
    customCol: "industry_custom",
  },
  {
    key: "culture",
    title: "What kind of culture do you thrive in?",
    subtitle: "Pick the vibes that match how you do your best work. ✨",
    options: CULTURE_OPTIONS,
    allowCustom: true,
    required: true,
    standardCol: "culture_standard",
    customCol: "culture_custom",
  },
  {
    key: "values",
    title: "What do you want the company to actually care about?",
    subtitle: "Pick the values that would make you proud to work there. 💛",
    options: VALUES_OPTIONS,
    allowCustom: true,
    required: true,
    standardCol: "values_standard",
    customCol: "values_custom",
  },
  {
    key: "dealbreakers",
    title: "Anything that is a firm no?",
    subtitle: "Add any boundaries you want us to never compromise on. You can skip this — not everyone has a deal-breaker. 🚧",
    options: null,
    allowCustom: true,
    required: false,
    standardCol: null,
    customCol: "dealbreakers",
    freeTextOnly: true,
  },
]
